apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
spec:
  replicas: 1   # Can scale later safely (Redis WS adapter)
  selector:
    matchLabels:
      app: nest-api
  template:
    metadata:
      labels:
        app: nest-api
    spec:
      containers:
        - name: nest-api
          image: nest-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config